# Generated by Django 5.2.5 on 2025-08-23 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='last_access_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата последнего доступа'),
        ),
    ]
